In [9]:
import numpy as np

In [10]:
data=np.genfromtxt('data/ratings.dat',delimiter='::',dtype=np.int64) #기본이 실수라 정수형으로
data[:10]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368]], dtype=int64)

In [11]:
print(data.shape)

(1000209, 4)


In [15]:
user_ids=np.unique(data[:, 0])
print(user_ids[:5])
print(user_ids.shape)

[1 2 3 4 5]
(6040,)


In [17]:
mean_values=[]
for user_id in user_ids:
  data_for_user=data[data[:,0]==user_id, :] #한 유저의
  value=data_for_user[:, 2].mean() #여러 평점만 가져와서 평균을 내라
  mean_values.append([user_id, value])

In [18]:
mean_values[:10] #이건 list

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606]]

In [19]:
#numpy로 적용하기

mean_array=np.array(mean_values, dtype=np.float32)
print(mean_array[:10])
print(mean_array.shape)

[[ 1.         4.188679 ]
 [ 2.         3.7131784]
 [ 3.         3.9019608]
 [ 4.         4.1904764]
 [ 5.         3.1464646]
 [ 6.         3.9014084]
 [ 7.         4.322581 ]
 [ 8.         3.884892 ]
 [ 9.         3.7358491]
 [10.         4.114713 ]]
(6040, 2)


In [21]:
np.savetxt('data/movie_result.csv', mean_array, fmt='%.2f', delimiter=',')

In [31]:
#영화 id별 평점 구하기-----------------------------------------제대로 안된듯 집에서 다시할것.
movieID=np.unique(data[:, 1]) #영화ID
print(movieID) #3952개인 것을 보니 영화데이터
print(movieID.shape) 

[   1    2    3 ... 3950 3951 3952]
(3706,)


In [33]:
mean_values_test=[]
for movie_id in movieID:
  data_for_movie=data[data[:,0]==movie_id, :] #한 영화의
  value=data_for_movie[:, 2].mean() #평점을 가져와서 평균을 내라
  mean_values_test.append([movie_id, value])

In [34]:
mean_values_test[:10] #10개만 확인

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606]]