In [7]:
import numpy as np

(기존 python이라면) 

pip install numpy

In [3]:
a=[1,2,3,4,5,'s']
b=np.array(a)
print(a ,type(a))
print(b, type(b))

[1, 2, 3, 4, 5, 's'] <class 'list'>
['1' '2' '3' '4' '5' 's'] <class 'numpy.ndarray'>


In [11]:
b1=np.arange(10)
b1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a=[[1,2,3],[4,5,6]]
b=np.array(a)
b
type(b)

array([[1, 2, 3],
       [4, 5, 6]])

a=[[1,2,3],[4,5,6]]
b=np.array(a)
b
type(b)   

이렇게 입력하면 type(b) 값만 나오고 b는 나오지 않음. 이런식으로 결과를 볼때 두가지 다 출력하고 싶다면 각각 print() 로 감싸줘야 한다.

In [19]:
a=[1,2,3,4,5,6]
b=np.array(a).reshape(2,3)
c=np.array(a).reshape(3,2)
print(b)

print("")

print(b.shape)
print(c.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)
(3, 2)


In [21]:
print(b[0][1])

print(b[0, 1])


2
2


In [23]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)

print(a)
print(b)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


list는 입력된 형태 그대로 나온거고,
numpy는 행렬형태로 나온다.

In [39]:
print(a[:][1]) 

print(b[:,1])

print(b[::-1][0,2])  

[4, 5, 6]
[2 5 8]
9


b에 저장된 값에서 2, 5, 8을 가져오고 싶을 때,
리스트는 특정 열 값만 가지고 올수 없음.
numpy는 가능

In [53]:
list1=[1,2,3]
list2=[4,5,6]
print(list1)
print(list1*3) #같은 list를 3번 반복
print(list2)
print(list1+list2)
# print(list1*list2) 안됨


print("")

arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
print(arr1)
print(arr1*2)
print(arr2)
print(arr1+arr2)
print(arr2*arr2)
print(arr2-arr2)
print(arr2/arr2)
print(arr2//arr2)


[1, 2, 3]
[4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 4, 5, 6]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[121 144 169]
 [196 225 256]
 [289 324 361]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [57]:
arr3=np.array([10,20,30])
print(arr3)
print(arr1*arr3)

[10 20 30]
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


In [65]:
print(arr1)

print(arr1.sum())
print(np.sum(arr1))

print(arr1.sum(axis=0)) #열의 합
print(np.sum(arr1, axis=0))
print(np.sum(arr1, axis=1)) #행의 합

print(arr1.mean()) #평균
print(arr1.mean(axis=0)) #열의 평균

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
45
[12 15 18]
[12 15 18]
[ 6 15 24]
5.0
[4. 5. 6.]


In [68]:
a=[5,3,2,4,1,7,6,9,8]
arr=np.array(a).reshape(3,3)
arr

array([[5, 3, 2],
       [4, 1, 7],
       [6, 9, 8]])

In [72]:
print(np.sort(arr)) #그냥 이렇게 하면 각 행을 오름차순으로 정렬

print(np.sort(arr, axis=0)) #열 기준

print(np.sort(arr, axis=1)) #행 기준 (맨위와 같음)

print(np.sort(arr, axis=0)[::-1, ::]) #열기준으로 정렬하고, 그 다음 행 순서를 역순으로
print(np.sort(arr, axis=0)[::, ::-1]) #열기준으로 정렬하고, 그 다음 열 순서를 역순으로

[[2 3 5]
 [1 4 7]
 [6 8 9]]
[[4 1 2]
 [5 3 7]
 [6 9 8]]
[[2 3 5]
 [1 4 7]
 [6 8 9]]
[[6 9 8]
 [5 3 7]
 [4 1 2]]
[[2 1 4]
 [7 3 5]
 [8 9 6]]


In [73]:
print(arr)
print(arr.transpose()) #좌측위->우측하단 으로 뻗는 대각선을 기준으로 역순 =전치행렬

[[5 3 2]
 [4 1 7]
 [6 9 8]]
[[5 4 6]
 [3 1 9]
 [2 7 8]]


In [76]:
print(arr>=5)
print(np.all(arr>3)) #데이터 모두가 3보다 큰가?
print(np.any(arr>3)) #3보다 큰 데이터가 하나는 있는가?

[[ True False False]
 [False False  True]
 [ True  True  True]]
False
True


In [81]:
a1=np.zeros(10) #0으로 10개 채워짐
print(a1)

b1=np.ones(10) #1로 10개 채워짐
print(b1)

a1=np.zeros([3,3]) 
print(a1)

b1=np.ones([4,5]) 
print(b1)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [84]:
print(arr.shape)

b1=np.ones_like(arr)
print(b1)

b2=np.zeros_like(arr)
print(b2)


(3, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
